### ISSUE TITLE
Chaining methods

### ISSUE THREAD

**Issue by johnathancroom** [ethnt/vermonster#3]
The objective shows that the lists should be retrieved like so: 

``` ruby
cheddar.lists.all
```

I have tried and tried, and I simply cannot figure out how to chain the methods like that. I'm sure it is probably something simple that is whizzing right over my head, but I need help.

I've already written some of the methods for lists but I need to figure this out to continue. 

Point me in the right direction, please.

**Comment by ethnt** [comment]
There are a few ways we can go about this.

One way is having the base method (`lists`) return `self`.

``` ruby
class Client
  def initialize(name)
    @name = name
  end

  def foo
    self
  end

  def bar
    @name
  end
end

hello = Client.new("Hello.")
hello.foo.bar # => "Hello."
```

Another way I was thinking is making `List`, `Task`, and `User` their own class with methods to create, modify, et cetera. We could use something like [toystore](https://github.com/jnunemaker/toystore) for that, and then alias that class to a method.

I'd just like to do that because I like the syntax—it's simple and easy to pick up. If it's too difficult, it wouldn't be terrible to do something like `cheddar::Lists.all`.

Any suggestions are appreciated.

**Comment by johnathancroom** [comment]
The problem with the first idea is that they can't have similar second methods. What if we wanted `hello.foo.bar` and `hello.two.bar` or in this case, `cheddar.tasks.find(34)` and `cheddar.lists.find(34)`.

I really like the syntax, too, and I'm checking out toystore now.

**Comment by ethnt** [comment]
For posterity, here's @johnathancroom's [solution](https://gist.github.com/3100723).

``` ruby
module Vermonster
  module Lists
    def lists
      self.class::Lists
    end

    class Lists
      def self.all
        Vermonster::Client.connection # Use this anywhere you want the connection
      end
    end
  end

  module Tasks
    def tasks
      self.class::Tasks
    end

    class Tasks
      def self.all
        "hi"
      end
    end
  end
end

module Vermonster
  class Client
    def connect!
      @@connection = [{"id" => 1, "crap" => "teag"}, {"id" => 2, "crap" => "yeah"}, {"id" => 3, "crap" => "yeah"}]
      self
    end

    def self.connection
      @@connection
    end

    include Lists
    include Tasks
  end
end

cheddar = Vermonster::Client.new
cheddar.connect!

puts cheddar.lists.all
puts cheddar.tasks.all
```
